import "./globals.css";
import { Products } from "@/components/products/Products";
import { ApolloWrapper } from "@/misc/apolloWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Products />
        </ApolloWrapper>
      </body>
    </html>
  );
}
